# Preview this course: https://dev-doctor.cf/

# The icon of the backend. Supported values are [png, jpg, svg, null]
icon: png

# The name of the course. You can see it in the title or in the list
name: Example course

# The author. It will appear on the front page and on the courses list
author: CodeDoctorDE

# The description of the course which can be seen in the list of the courses and the intro page.
description: >
  This course is only an example which
  shows how this config works
  
# The body is posting on the home page of the course page. Source: https://remarkjs.github.io/react-markdown/
body: |
  Changes are automatically rendered as you type.

  * Implements [GitHub Flavored Markdown](https://github.github.com/gfm/)
  * Renders actual, "native" React DOM elements
  * Allows you to escape or skip HTML (try toggling the checkboxes above)
  * If you escape or skip the HTML, no `dangerouslySetInnerHTML` is used! Yay!

  ## Table of Contents

  ## HTML block below

  <blockquote>
    This blockquote will change based on the HTML settings above.
  </blockquote>

  ## How about some code?

  ```js
  var React = require('react');
  var Markdown = require('react-markdown');

  React.render(
    <Markdown source="# Your markdown here" />,
    document.getElementById('content')
  );
  ```

  Pretty neat, eh?

  ## Tables?

  | Feature   | Support |
  | :-------: | ------- |
  | tables    | ✔ |
  | alignment | ✔ |
  | wewt      | ✔ |

  ## More info?

  Read usage information and more on [GitHub](https://github.com/remarkjs/react-markdown)

  ---------------

  A component by [Espen Hovlandsdal](https://espen.codes/)

# The current category of the course. You can see the categories in the list
category: []

# The language of the course. You can see a flag as a badge of the course.
lang: en

# Controls if the course is shown in the list
private: true

# The course. See the preview to understand all config entries
parts:
- part-1
- part-2



