# Preview this course: https://dev-doctor.cf/

# The icon of the course. Supported values are [png, jpg, svg, null]
icon: null

# The name of the course. You can see it in the title or in the list
name: Example course 2

# The author. It will appear on the front page and on the courses list
author: CodeDoctorDE

# The description of the course which can be seen in the list of the courses and the intro page.
description: >
  This course is only an example which
  shows how this config works -- 2
  
# The body is posting on the home page of the course page
body: |
  This is the body

# The current category of the course. You can see the categories in the list
category: []

# The language of the course. You can see a flag as a badge of the course.
lang: en

# Controls if the course is shown in the list
private: true

# The course. See the preview to understand all config entries
parts:
- part-1



