# The name of the current part. The name will stand on the sidebar
name: Part 1

# Optional: The description of the part
description: This is a description

# Assets which will be cached if the user is offline. The assets need to be in the asset directory
assets: []

# The content of the part.
items:
- name: Welcome
  description: Welcome to the course
  type: video
  source: url
  url: https://backend.dev-doctor.cf/example/part-1/assets/video.mp4
- name: Text
  type: text
  text: >
    Here you can write something. Markdown is supported!
- name: Quiz
  # Optional: Max time in seconds (here: 10 minutes)
  time: 600
  type: quiz
  questions:
  - title: Question 1 title
    description: Question 1 description
    evaluation: An evaluation
    answers:
    - name: A
    - name: B
    - name: C
      points: 5
      correct: true
    - name: D
      points: 2
      correct: true
  - title: Question 2 title
    description: Question 2 description
    evaluation: An evaluation for question 2
    answers:
    - name: A
      correct: true
    - name: B
      correct: true
    - name: C
    - name: D